spring:
  application:
    name: AgricultureProductsManagement
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1
  mvc:
    view:
      prefix: /
      suffix: .jsp

server:
  port: 8080
